voice_group fightsong1           
	voice_keysplit_all voicegroup_emerald_drumset_1
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings 
	voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet 
	voice_keysplit voicegroup_tuba_keysplit, keysplit_tuba 
	voice_keysplit voicegroup_french_horn_keysplit, keysplit_french_horn 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute                        , 255, 127, 231, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani                      , 255, 246,   0, 226  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2                       , 255,   0, 255, 206  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp                         , 255, 242,  51, 242  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell                , 255, 165,  90, 216  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass                , 255, 253,   0, 188  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash       , 255, 235,   0, 231  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass                   , 255, 252,   0, 115  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_ambient_tom                     , 255,   0, 255, 226  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings            , 255, 216,   0, 165  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone                    , 255, 235,   0, 204  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass                    , 255, 235, 128,  99  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_open_triangle                   , 255, 242, 103, 188  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion                    , 255,   0, 255, 165  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_open_low_conga               , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass                , 255, 253,   0, 149  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low       , 255, 188, 128, 226  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel                 , 255, 165,  51, 242  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar      , 255,   0, 255, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_rnd_snare                    , 255,   0, 255, 242  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_snare              , 255,   0, 255, 242  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255,   0, 255, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low , 255,   0, 255, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high      , 255, 204,  77, 246  
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc55_tom                      , 255, 210,  77, 204  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_mute_high_conga              , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane            , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tr909_hand_clap              , 255, 255, 255, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tambourine                   , 255, 127,  77, 204  
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_kotsuzumi            , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave                  , 255,   0, 255, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_solo_snare                      , 255, 180, 175, 228  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_taiko                        , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_trinity_cymbal_crash                 , 255, 231,   0, 188  
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_ohtsuzumi            , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_jingle_bell                  , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs           , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_hyoushigi            , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_dance_drums_ride_bell                , 255, 165, 103, 231  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_cowbell                         , 255,   0, 255, 242  
	voice_directsound 60, 0, DirectSoundWaveData_unused_heart_of_asia_indian_drum     , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe                     , 255, 216, 200, 165  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_rnd_kick                     , 255,   0, 255, 242  
	voice_directsound 60, 0, DirectSoundWaveData_drum_and_percussion_kick             , 255,   0, 255,   0  
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap           , 255, 165, 180, 216  
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass              , 255, 178, 180, 165  
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned                    , 255, 165, 154, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe                  , 255, 165, 154, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi            , 255,   0, 255, 204  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_72           , 255,   0, 255, 196  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_french_horn_72               , 255,   0, 218, 165  
	voice_directsound 60, 0, DirectSoundWaveData_bicycle_bell                         , 255, 249,   0, 165  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles                      , 255,   0, 255, 127  
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord  , 255, 165, 206, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_48                    , 255, 252,   0, 239  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_60                    , 255, 250,   0, 221  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_72                    , 255, 250,   0, 221  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_84                    , 255, 247,   0, 221  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60           , 255,   0, 255, 196  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_84           , 255,   0, 255, 196  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_60                   , 255,   0, 193, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_72                   , 255,   0, 193, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_84                   , 255,   0, 193, 127  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tuba_39                      , 255,   0, 255, 165  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tuba_51                      , 255,   0, 255, 165  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_french_horn_60               , 255,   0, 224, 165  
	voice_directsound 60, 0, DirectSoundWaveData_heart_of_asia_gamelan                , 255, 188, 139, 239  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low            , 255,  76, 154, 188  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high           , 255,  76, 154, 188  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani_with_snare           , 255, 246,   0, 226  
	voice_programmable_wave 60, 0, ProgrammableWaveData_10, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_10, 0, 7, 15, 0 
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 6, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 4, 1
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 5, 1
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 4, 1
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0  
	voice_noise 60, 0, 0, 0, 1, 0, 1
	voice_noise 60, 0, 0, 0, 1, 4, 1
	voice_programmable_wave 60, 0, ProgrammableWaveData_5, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0 
    voice_square_2_alt 60, 0, 0, 0, 7, 10, 1
    voice_square_2_alt 60, 0, 2, 0, 1, 8, 1
	voice_square_2_alt 60, 0, 3, 0, 1, 8, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 8, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 9, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15,1
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 0, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_15, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_16, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_11, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_2, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_3, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_4, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_7, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_8, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_9, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_17, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_18, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_19, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_20, 0, 7, 15, 0 
	voice_programmable_wave 60, 0, ProgrammableWaveData_21, 0, 7, 15, 0 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 76
	voice_square_1 60, 0, 0, 1, 0, 1, 9, 0
	voice_square_1 60, 0, 0, 1, 0, 1, 9, 0
	voice_square_1 60, 0, 0, 1, 0, 1, 9, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_22, 0, 7, 15, 0 
	voice_directsound 60, 0, DirectSoundWaveData_register_noise, 255, 0, 255, 76
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion_duplicate, 255, 249, 25, 248
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 195
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242
	voice_keysplit_all voicegroup_emerald_drumset_1
	voice_directsound_alt 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242
	voice_directsound_alt 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242


