#ifndef GUARD_GENERATED_ANIM_CODE_Tarc3OutsideShip_H
#define GUARD_GENERATED_ANIM_CODE_Tarc3OutsideShip_H

// Ensure INCBIN_U16 is available
#ifndef INCBIN_U16
#include "gba/defines.h"
#endif

/*
 * This file is auto-generated by Porytiles.
 * DO NOT EDIT THIS FILE MANUALLY (unless you know what you are doing).
 */

// ============================================
// Frame Data (INCBIN statements)
// ============================================

const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame0[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame1[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame2[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame3[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame4[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame5[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame6[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/6.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame7[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_a/7.4bpp");

const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame0[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame1[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame2[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame3[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame4[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame5[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame6[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/6.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame7[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/calm_water_b/7.4bpp");

const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower_FrameCenter[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/flower/center.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower_FrameRight[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/flower/right.4bpp");
const u16 gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower_FrameLeft[] = INCBIN_U16("data/tilesets/primary/tarc3_outside_ship/porytiles_bin/anim/flower/left.4bpp");

// ============================================
// Frame Pointer Arrays
// ============================================

const u16 *const gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA[] = {
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame0,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame1,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame2,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame3,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame4,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame5,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame6,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA_Frame7
};

const u16 *const gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB[] = {
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame0,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame1,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame2,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame3,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame4,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame5,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame6,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB_Frame7
};

const u16 *const gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower[] = {
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower_FrameCenter,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower_FrameRight,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower_FrameCenter,
    gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower_FrameLeft
};

// ============================================
// Queue Functions
// ============================================

static void QueueAnimTiles_PorytilesManaged_Tarc3OutsideShip_CalmWaterA(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterA[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(1)), 1 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_Tarc3OutsideShip_CalmWaterB(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_CalmWaterB[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(2)), 1 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_Tarc3OutsideShip_Flower(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_Tarc3OutsideShip_Flower[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(3)), 4 * TILE_SIZE_4BPP);
}

// ============================================
// Driver Function
// ============================================

static void TilesetAnim_PorytilesManaged_Tarc3OutsideShip(u16 timer)
{
    if (timer % 16 == 0)
    {
        QueueAnimTiles_PorytilesManaged_Tarc3OutsideShip_Flower(timer / 16);
    }
    if (timer % 16 == 1)
    {
        QueueAnimTiles_PorytilesManaged_Tarc3OutsideShip_CalmWaterA(timer / 16);
        QueueAnimTiles_PorytilesManaged_Tarc3OutsideShip_CalmWaterB(timer / 16);
    }
}

// ============================================
// Init Function
// ============================================

void InitTilesetAnim_PorytilesManaged_Tarc3OutsideShip(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_PorytilesManaged_Tarc3OutsideShip;
}

#endif // GUARD_GENERATED_ANIM_CODE_Tarc3OutsideShip_H
